import {
  PrismaClient,
  GearType,
  RateOfFire,
  Range,
  Reliability,
  ArmorType,
} from '@prisma/client';

export async function seedItems(prisma: PrismaClient) {
  // Upsert Items
  console.log('Upserting Items...');
  const items = [
    {
      id: 1,
      name: 'Dagger',
      type: GearType.MELEE,
      rank: 1,
      damageUnarmored: 2,
      damageArmored: -4,
      concealable: true,
      twoHanded: false,
      reach: false,
      finesse: true,
      thrown: true,
      range: Range.NEARBY,
      scatter: false,
      sniper: false,
      brace: false,
    },
    {
      id: 2,
      name: 'Pistol - Automatic',
      type: GearType.RANGED,
      rank: 1,
      damageUnarmored: 3,
      damageArmored: -3,
      concealable: false,
      twoHanded: false,
      reach: false,
      finesse: false,
      thrown: false,
      attacksWorthOfAmmo: 6,
      rateOfFire: RateOfFire.BURST,
      range: Range.MEDIUM,
      reliability: Reliability.NORMAL,
      scatter: false,
      sniper: false,
      brace: false,
    },
    {
      id: 3,
      name: 'Shotgun - Pump',
      type: GearType.RANGED,
      rank: 1,
      damageUnarmored: 4,
      damageArmored: -4,
      concealable: false,
      twoHanded: true,
      reach: false,
      finesse: false,
      thrown: false,
      attacksWorthOfAmmo: 6,
      rateOfFire: RateOfFire.SINGLE,
      range: Range.MEDIUM,
      reliability: Reliability.NORMAL,
      scatter: true,
      sniper: false,
      brace: false,
    },
    {
      id: 4,
      name: 'CAF Active Wear',
      type: GearType.ARMOR,
      rank: 1,
      concealable: false,
      twoHanded: false,
      reach: false,
      finesse: false,
      thrown: false,
      scatter: false,
      sniper: false,
      brace: false,
      armorType: ArmorType.OUTFIT,
      soak: 0,
    },
    {
      id: 5,
      name: 'Body Blocker',
      type: GearType.ARMOR,
      rank: 1,
      concealable: false,
      twoHanded: false,
      reach: false,
      finesse: false,
      thrown: false,
      scatter: false,
      sniper: false,
      brace: false,
      armorType: ArmorType.HARDENED,
      soak: 0,
    },
    {
      id: 6,
      name: 'BLA Blitzer',
      type: GearType.RANGED,
      rank: 4,
      damageUnarmored: 5,
      damageArmored: 5,
      concealable: false,
      twoHanded: false,
      reach: false,
      finesse: false,
      thrown: false,
      attacksWorthOfAmmo: 3,
      rateOfFire: RateOfFire.SINGLE,
      range: Range.MEDIUM,
      scatter: false,
      sniper: false,
      brace: false,
    },
    {
      id: 7,
      name: 'FEN 603',
      type: GearType.RANGED,
      rank: 2,
      damageUnarmored: 3,
      damageArmored: -3,
      concealable: false,
      twoHanded: false,
      reach: false,
      finesse: false,
      thrown: false,
      attacksWorthOfAmmo: 6,
      rateOfFire: RateOfFire.BURST,
      range: Range.MEDIUM,
      reliability: Reliability.RELIABLE,
      scatter: false,
      sniper: false,
      brace: false,
    },
  ];
  for (const item of items) {
    const { id, ...itemData } = item;
    await prisma.item.upsert({
      where: { id },
      update: itemData,
      create: { id, ...itemData },
    });
  }
}
